version: '3.7'
services:
  con-observer:
    image: con-observer
    working_dir: /con-obs
    volumes:
      - ./:/con-obs
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - REMOVE_CON_IF_EMPTY_DB=true
      - SCHEDULE=*/16 * * * *
      - CON_DB_QUERY_SQL=select distinct __CON_DB_QUERY_FIELDS__ from __CON_DB_NAME__
      - CON_DB_QUERY_FIELDS=NAME,DESCRIPTION,SRCDEVICE,SRCINTERFACE,DSTDEVICE,DSTINTERFACE
      - CON_DB_NAME=CONNECTIONS
      - CON_DB_USER=sunrise
      - CON_DB_PW=oadvice
      #- CON_DB_CON=192.168.12.200:1521/ORCL
      - CON_DB_CON=(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.12.200)(PORT = 1521))(CONNECT_DATA =(SID= ORCL)))
      - ASM_BASE_URL=https://192.168.12.226/1.0/rest-observer/rest/
      - ASM_TOPO_URL=https://192.168.12.226/1.0/topology/
      - ASM_USER=asm
      - ASM_PASS=asm
      - ASM_TENANT_ID=cfd95b7e-3bc7-4006-a4a8-a73a79c71255
      - ASM_EP_JOB_ID=snr_inventory
      - ASM_EP_RES=resources
      - ASM_EP_REF=references
      - ASM_EP_REF_DEL=/references/out/contains?_delete=nodes&_delete_self=false
      - ASM_EP_RES_FLT=?_filter=entityTypes%3D__ASM_ENTITY_TYPE__&_field=uniqueId&_limit=999999999&_include_global_resources=false&_include_count=false&_include_status=false&_include_status_severity=false&_include_metadata=false&_return_composites=true
      - TZ=Europe/Berlin
      - DELETE_IF_NOT_PRESENT_IN_INV=true
      - ASM_EP_RES_DEL_IMMEDIATE=true
      - ASM_EP_DEL_WAIT_TIME_MS=6000
      - ASM_EP_RES_DEL_IMMEDIATE_PARAM=?_immediate=true
      - ASM_ENTITY_TYPE=networkDevice
      - ASM_ENTITY_TYPE_IF=networkInterface
    command: 'npm run dev'
